var routes = [
    {
        id: "dashboard",
        path: "/dashboard/",
        name: "Dashboard",
        icon: "ni ni-tv-2 text-primary",
        layout: "/admin",
    },
    {
        id: "client",
        path: "/icons/",
        name: "Contacts",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
        nestedPage: [
            {
                path: "/Clients/",
                name: "Clients",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Groups",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Add Client",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Add Group",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
        ],
    },
    {
        id: "practice",
        path: "/icons/",
        name: "Practice Management",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
        nestedPage: [
            {
                path: "/icons/",
                name: "My Timesheet",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Jobs",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Job Orders",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Recurring Jobs",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Add Job",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Add Jobs in Bulk",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Add Recurring Jobs",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
        ],
    },
    {
        id: "reports",
        path: "/icons/",
        name: "Reports",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
        nestedPage: [
            {
                path: "/icons/",
                name: "Job Due's",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Timesheet",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Custom Reports",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Other Report",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
        ],
    },
    {
        id: "data",
        path: "/icons/",
        name: "Data Management",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
        nestedPage: [
            {
                path: "/icons/",
                name: "Import Contacts",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Import Jobs",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Export Contacts",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
        ],
    },
    {
        id: "user",
        path: "/icons/",
        name: "User Management",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
        nestedPage: [
            {
                path: "/icons/",
                name: "Add Users",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Add Roles",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Manage Users",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
        ],
    },
    {
        id: "settings",
        path: "/icons/",
        name: "Settings",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
        nestedPage: [
            {
                path: "/icons/",
                name: "Locations",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
            {
                path: "/icons/",
                name: "Job Settings",
                icon: "ni ni-planet text-blue",
                layout: "/admin",
            },
        ],
    },
    // {
    //     id: "icons",
    //     path: "/icons/",
    //     name: "Icons",
    //     icon: "ni ni-planet text-blue",
    //     layout: "/admin",
    // },
    // {
    //     path: "/maps",
    //     name: "Maps",
    //     icon: "ni ni-pin-3 text-orange",
    //     layout: "/admin",
    // },
    // {
    //     path: "/profile",
    //     name: "User Profile",
    //     icon: "ni ni-single-02 text-yellow",
    //     layout: "/admin",
    // },
    // {
    //     path: "/tables",
    //     name: "Tables",
    //     icon: "ni ni-bullet-list-67 text-red",
    //     layout: "/admin",
    // },
    // {
    //     path: "/login",
    //     name: "Login",
    //     icon: "ni ni-key-25 text-info",
    //     layout: "/auth",
    // },
    // {
    //     path: "/register",
    //     name: "Register",
    //     icon: "ni ni-circle-08 text-pink",
    //     layout: "/auth",
    // },
];
export default routes;
