var routes = [
    {
        id: "dashboard",
        path: "/dashboard/",
        name: "Dashboard",
        icon: "ni ni-tv-2 text-primary",
        layout: "/admin",
    },
    {
        id: "ETH",
        path: "/dashboard/",
        name: "Ethereum",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
    },
    {
        id: "BTC",
        path: "/dashboard/",
        name: "Bitcoin",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
    },
    {
        id: "ARB",
        path: "/maps/",
        name: "Arbitrum",
        icon: "ni ni-map-big text-blue",
        layout: "/admin",
    },
    {
        id: "USDT",
        path: "/tables/",
        name: "Tether",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
    },
    {
        id: "XRP",
        path: "/icons/",
        name: "XRP",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
    },
    {
        id: "BUSD",
        path: "/icons/",
        name: "Binance USD",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
    },
    {
        id: "DOGE",
        path: "/icons/",
        name: "Dogecoin",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
    },
    {
        id: "SOL",
        path: "/icons/",
        name: "Solana",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
    },
    {
        id: "ADA",
        path: "/icons/",
        name: "Cardano",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
    },
    {
        id: "BNB",
        path: "/icons/",
        name: "Binance Coin",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
    },
    {
        id: "icons",
        path: "/icons/",
        name: "Icons",
        icon: "ni ni-planet text-blue",
        layout: "/admin",
    },
];
export default routes;
